# Generated by Django 2.2 on 2020-05-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200529_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='isbn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
