# Generated by Django 2.2 on 2020-06-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200531_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
    ]
